<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable=[
        'name',
    ];

    public function products(){
        return $this->hasMany('App\Product');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function(Category $category) {
           $category->products()->delete();
        });
    }
}
