<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WorkType extends Model
{
    protected $fillable=[
        'name',
    ];
    public function prices(){
        return $this->hasMany('App\Price');
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function(WorkType $work_type){
            $work_type->prices()->delete();
        });
    }
}
